# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a7d314438b33fb1e858801d4f51a0c2f90a0e4613987c0a8fa48f7a0ee014ce4704d758d9c0d32282c528f513e8fec5b4f04878779b61e60db1031cdf2f8c64

test:
  secret_key_base: 9d4604f32529eff75b0a245417f366edad4723a81a102ad41c8f62c22420a35ae8852c82121d8d37ba247af22f577c3001904d43a941cb79c878e529540d4ca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
